language: rust

install:
  - sudo add-apt-repository ppa:team-xbmc/ppa -y
  - sudo apt-get update -q
  - sudo apt-get install libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev

rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly