environment:
  matrix:
  - TARGET: x86_64-pc-windows-msvc
    SDL_TARGET: x86_64
  - TARGET: i686-pc-windows-msvc
    SDL_TARGET: i686
  - TARGET: i686-pc-windows-gnu
    SDL_TARGET: i686
install:
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.exe"
  - rust-nightly-%TARGET%.exe /VERYSILENT /NORESTART /DIR="C:\Program Files (x86)\Rust"
  - SET PATH=%PATH%;C:\Program Files (x86)\Rust\bin
  - SET PATH=%PATH%;C:\MinGW\bin
  - ps: Start-FileDownload "https://www.libsdl.org/release/SDL2-devel-2.0.4-mingw.tar.gz"
  - ps: 7z x SDL2-devel-2.0.4-mingw.tar.gz
  - ps: 7z x SDL2-devel-2.0.4-mingw.tar
  - ps: Copy-Item "SDL2-2.0.4\${env:SDL_TARGET}-w64-mingw32\lib\SDL2*.lib" "C:\Program Files (x86)\Rust\bin\rustlib\${env:SDL_TARGET}-pc-windows-gnu\lib\"
  - rustc -V
  - cargo -V
build: false

test_script:
  - cargo test --verbose