[package]

name = "rust64"
version = "0.0.1"
authors = [ "Krzysztof Kondrak <krzysztof.kondrak@gmail.com>" ]

[dependencies]

sdl2 = "*"
time = "*"
minifb = { git = "https://github.com/emoon/rust_minifb.git" }